spring:
  main:
    banner-mode: "off"
#  profiles:#    active: dev
    
  thymeleaf:   # thymeleaf
    servlet:
      content-type: text/html
    cache: false
    encoding: UTF-8
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.253.33.91:1521:SCANDEV
    username: sboutgj
    password: fuyr287zbuhf7zo
#  
#    hikari:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      jdbc-url: jdbc:oracle:thin:@10.253.33.91:1521:SCANDEV
#      username: sboutgj
#      password: fuyr287zbuhf7zo
#      connection-timeout: 60000 # UNIT : ms

  jpa:          # jpa
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect 
     


server:
  error:
    include-stacktrace: never
    path: '/error'
  port: 9030
